### ISSUE TITLE
Problem with fsmc

### ISSUE THREAD

**Issue by hpexeph** [eepj/DS1307_for_STM32_HAL#1]
Hi
Thanks for sharing these codes
When I use it alone with serial port, I do not have any problem but when use a LCD with fsmc, it does not work

**Comment by eepj** [comment]
Hello and sorry about the error. I understand that the SHT2x and DS1307 both have issues with FSMC?

**Comment by hpexeph** [comment]
Hi . both have issues and I do not know why
